### ISSUE TITLE
Lazier arrays?

### ISSUE THREAD

**Issue by noughtmare** [lehins/massiv#111]
I was implementing a dynamic programming problem with my favorite array library (massiv :smile:) lately. But, I noticed that massiv evaluates all array elements to WHNF which causes problems with cyclical dependencies. Here is a small program that calculates fibonacci numbers as an example:

```Haskell
import Data.Massiv.Array

fib :: Int -> Int
fib n = arr ! n where
  arr = makeArrayR B Seq (Sz1 (n + 1)) gen
  gen (Ix1 i)
    | i < 2 = i
    | otherwise = (arr ! i - 1) + (arr ! i - 2)
```

This gets stuck in an infinite loop. I can work around it by introducing a wrapper data type that keeps its content lazy:

```Haskell
import Data.Massiv.Array

data Wrap a = Wrap { unwrap :: a }

fib :: Int -> Int
fib n = unwrap (arr ! n) where
  arr = makeArrayR B Seq (Sz1 (n + 1)) gen
  gen (Ix1 i)
    | i < 2 = Wrap i
    | otherwise = Wrap $ unwrap (arr ! i - 1) + unwrap (arr ! i - 2)
```

But this is ugly and probably slightly less efficient. Can a new type of array be added that does not evaluate its elements to WHNF? Or is there already another way to do this?

**Comment by lehins** [comment]
I expected that this question would come up eventually. For now your `Wrap` approach is the only one that is available. I was trying to be really reluctant in adding lazy arrays, because for efficiency reasons arrays are almost always better strict and even better unboxed. I am sure that for theoretical reasons lazy arrays can come in handy sometimes, but my goal in massiv is really performance. For example `fib` would be better implemented using primitive array and mutable interface instead of pure, boxed and lazy:

```haskell
import Data.Massiv.Array as A

fib :: Int -> Int
fib n
  | n < 2 = n
  | otherwise = arr ! n
  where
    arr :: Vector P Int
    arr =
      createArrayST_ (Sz1 (n + 1)) $ \marr -> do
        writeM marr 0 0
        writeM marr 1 1
        A.forM_ (2 ... n) $ \i -> do
          x <- (+) <$> A.readM marr (i - 1) <*> A.readM marr (i - 2)
          writeM marr i x
```

That being said, I will keep this ticket opened and will try add `BL` (boxed lazy) representation some time soon. It's not hard at all, I was just waiting for some real demand for it, I guess.

By the way, I think `Integer` would be a bit more compelling example, since `Int` isn't enough for large Fibonacci numbers: and `Integer` can't be stored in unboxed vector:

```haskell
fib :: Int -> Integer
fib n = unwrap (arr ! n) where
  arr = makeArrayR B Seq (Sz1 (n + 1)) gen
  gen (Ix1 i)
    | i < 2 = Wrap $ fromIntegral i
    | otherwise = Wrap $ unwrap (arr ! i - 1) + unwrap (arr ! i - 2)
```

**Comment by lehins** [comment]
@noughtmare by the way, just realized that `fib` would be faster done this way:
```haskell
fib'' :: Int -> Integer
fib'' n
  | n < 2 = fromIntegral n
  | otherwise = arr ! (n `mod` 3)
  where
    arr :: Vector B Integer
    arr =
      createArrayST_ (Sz1 3) $ \marr -> do
        unsafeWrite marr 0 0
        unsafeWrite marr 1 1
        A.forM_ (2 ... n) $ \i -> do
          x <- (+) <$> unsafeRead marr ((i - 1) `mod` 3) <*> unsafeRead marr ((i - 2) `mod` 3)
          unsafeWrite marr (i  `mod` 3) x
```

However, it's really orthogonal to this issue. I just wanted to mention it for fun ;)

**Comment by noughtmare** [comment]
My real use case is closer to this version of the subset sum problem where repeats are allowed:

```Haskell
module Main where

import Prelude as P
import Data.Massiv.Array as A
import Data.Word

-- I just noticed that Wrap actually conflicts with Data.Massiv.Core.Index.Wrap
data Lazy a = Lazy { force :: a }

subsetSum :: [Int] -> Int -> Bool
subsetSum xs n = get n where
  arr = makeArrayR B Seq (Sz1 (n + 1)) (Lazy . gen)
  gen (Ix1 0) = True
  gen (Ix1 i) = P.any (\x -> get (i - x)) xs
  get i = 0 <= i && i <= n && force (arr ! i)

main :: IO ()
main = do
  putStrLn ("subset sum {34, 4, 12, 5} 9: " ++ show (subsetSum [34,4,12,5] 9))
  putStrLn ("subset sum {34, 4, 12}    9: " ++ show (subsetSum [34,4,12] 9))
```

Here it can happen that many positions in the array are never evaluated, so I think a lazy solution is really the fastest for this type of problem. Maybe something that continuously extracts the minimum element from a set and inserts new updates values would take less space and be just as fast.

---

P.S. If you want really fast Fibonacci generation then you can use this semigroup:

```Haskell
import Data.Semigroup

data Fib = Fib Integer Integer

instance Semigroup Fib where
  Fib x1 y1 <> Fib x2 y2 = Fib (x2 * x1 + y2 * y1) (y2 * x1 + (x2 + y2) * y1)

fib :: Integer -> Integer
fib 0 = 0
fib n = (\(Fib _ x) -> x) (stimes n (Fib 0 1))
```

This takes O(log n) time. Or O(b) where b is the number of bits in the input.

**Comment by lehins** [comment]
> If you want really fast Fibonacci generation then you can use this semigroup:

This is awesome, thanks for sharing :+1: 

You really have me convinced now that lazy arrays are useful. I'll add it in the next upcoming release massiv-0.6.0 which is not far away.
