### ISSUE TITLE
[massiv] Odd stencil indexing?

### ISSUE THREAD

**Issue by fosskers** [lehins/massiv#12]
[The stencil section](https://github.com/lehins/massiv#stencil) of the README implies that neighbourhood indexing works like this:
```
| (-1, -1) | (-1, 0) | (-1, 1) |
--------------------------------
| (0, -1)  | (0, 0)  | (0, 1)  |
--------------------------------
| (1, -1)  | (1, 0)  | (1, 1)  |
```
and yet:
```
> makeArrayR U Seq (3 :. 3) (\(r :. c) -> (r * 3) + c + 1)
(Array U Seq (3 :. 3)
  [ [ 1,2,3 ]
  , [ 4,5,6 ]
  , [ 7,8,9 ]
  ])

> computeAs U . zag $ makeArrayR U Seq (3 :. 3) (\(r :. c) -> (r * 3) + c + 1)
(Array U Seq (3 :. 3)
  [ [ 0,1,2 ]
  , [ 0,4,5 ]
  , [ 0,7,8 ]
  ])
```
where:
```haskell
fidSten :: Default a => Stencil Ix2 a a
fidSten = makeStencil (Fill def) (3 :. 3) (1 :. 1) $ \f -> f (0 :. 1)

zag :: (Default a, Manifest r Ix2 a) => Array r Ix2 a -> Array DW Ix2 a
zag a = mapStencil fidSten a
```
It looks like `f (0 :. 1)` is grabbing the cell to the left, not the right as I had expected.

Any idea what's going on? (I found this deep down the debugging rabbit-hole)

**Comment by lehins** [comment]
@fosskers You are absolutely right! This is an ugly bug. I made a mistake of testing the stencil only on things that are symmetric, that's why didn't notice that behavior. Working on a patch.

**Comment by lehins** [comment]
@fosskers Thank you for finding this. I know why even made this error, I was using convolution as basis for the stencil which requires for such an inverse indexing.
Could you please validate that the fix works and I'll make a new release right away.

**Comment by fosskers** [comment]
Testing with:
```
extra-deps:
  - git: https://github.com/lehins/massiv
    commit: fa3f71099db90bdd6a0dd27c6447745c35d3df49
    subdirs:
      - massiv
```

**Comment by fosskers** [comment]
The fix works! Thank you kindly :)
