### ISSUE TITLE
Convert `Array U Ix1 a` to `Unboxed.Vector a` without copying

### ISSUE THREAD

**Issue by kozross** [lehins/massiv#137]
I have an `Unbox a => Array U Ix1 a`, and want to convert it to `Unboxed.Vector a` without copying it. Is this possible, and if so, how?

My context is this: I want to make use of `nthBitIndex` from [`bitvec`](https://hackage.haskell.org/package/bitvec-1.1.5.0/docs/Data-Bit.html#v:nthBitIndex), but I am using Massiv arrays instead, which seems to make using this operation impossible without first copying.

**Comment by lehins** [comment]
[`castToVector`](https://hackage.haskell.org/package/massiv-1.0.4.0/docs/Data-Massiv-Array-Manifest-Vector.html#v:castToVector) is the function that you are looking for.
