### ISSUE TITLE
[massiv-io - bug?] `readImageAuto` assumes conversion?

### ISSUE THREAD

**Issue by fosskers** [lehins/massiv#22]
I just hit a funny error in my tests. I have a function `fromGray` which is supposed to read any image type and produce a grayscale Raster. It uses `readImageAuto` for this under the hood.

When reading an already grayscale image just now, I got a runtime error:
```
ConvertError "Cannot decode Auto TIF image <Image S Y Word8> as <Image S Y Word8>"
```
Is this expected, or should `readImageAuto` attempt no conversion when it detects that the desired type and actual type are the same?

**Comment by lehins** [comment]
This doesn't look like expected behavior at all. That's the point of `Auto` to do all the necessary conversions, and should work especially when no conversion is necessary. Could you please attach a sample image so I can investigate it a bit further.

**Comment by fosskers** [comment]
GIthub doesn't seem to like TIFs, so I'll email it to you if that's alright.

**Comment by fosskers** [comment]
Sent.

**Comment by lehins** [comment]
Got it, thanks, I'll let you know whats up later on today.

**Comment by fosskers** [comment]
Thank you! Here's the code in question, in case that matters:
```haskell
-- | Read a grayscale image. If the source file has more than one colour band,
-- they'll be combined automatically.
fromGray :: forall p r c a. (Elevator a, KnownNat r, KnownNat c) => FilePath -> IO (Either String (Raster S p r c a))
fromGray fp = do
  cap <- getNumCapabilities
  img <- setComp (bool Par Seq $ cap == 1) <$> readImageAuto fp
  let rows = fromInteger $ natVal (Proxy :: Proxy r)
      cols = fromInteger $ natVal (Proxy :: Proxy c)
      (r :. c) = size img
  pure . bool (Left $ printf "Expected Size: %d x %d - Actual Size: %d x %d" rows cols r c) (Right $ f img) $ r == rows && c == cols
  where f :: Image S Y a -> Raster S p r c a
        f (delay -> img) = strict S . Raster $ (\(PixelY a) -> a) <$> img
```

**Comment by fosskers** [comment]
The delay-fmap-computeAs isn't the most ideal, but gives the type that people would want. You'd read an image and expect it to be a `Manifest` type so that you could do Focal (stenciled) operations right away.

**Comment by lehins** [comment]
@fosskers Thanks for reporting this issue. I added a fix and will release a new version of `massiv-io` momentarely.

As far as "delay-fmap-computeAs" goes, you are better of using `Data.Massiv.Array.map` instead of `<$>`, then you don't need to do `delay`, which might be faster. 

 I also noticed huge performance difference between `fromGray` and `fromRGBA`, I am really curious what could that be. Quiet often I'd a fix  for such a big drop in performance would be an addition of `{-# INLINE f #-}` pragmas. Worth experimenting.

**Comment by lehins** [comment]
@fosskers By the way, here is one more ugly thing that will work if you want to squeeze all the performance out of `fromGray` function. `Image S Y Word8` has the same memory representation as `Array S Ix2 Word8`, which means you could avoid copying the whole image by doing a cast:
```
f :: Image S Y a -> Raster S p r c a
f img = Raster . fromVector (getComp img) (size img) . V.unsafeCast . toVector $ img
```

**Comment by fosskers** [comment]
re: `map`. Nice! I didn't know that existed - I was transfixed by which `Array r` had a `Functor` instance.

re: casting. To do that cast, would I have to *know* that the input type was `Word8`? Your example and my actual code both operate over `a`.

**Comment by fosskers** [comment]
Ah ha! Nice, I'll try that.

**Comment by fosskers** [comment]
```
benchmarking IO/fromGray Multiband 512x512
time                 154.5 ms   (151.9 ms .. 160.2 ms)
             
benchmarking IO/fromGray Singleband 512x512
time                 6.294 ms   (6.112 ms .. 6.446 ms)
```
:)

The first benchmark is reading in a RGBA raster and having `readImageAuto` force it into grayscale. The second benchmark is reading in the grayscale as-is. Thanks for the fix!

**Comment by fosskers** [comment]
Honestly that conversion isn't a super priority for me either. It's mostly just a cool thing that it's even possible. People would appreciate the ability to do that while debugging their raster operations, I'm thinking.
