### ISSUE TITLE
Performance degradation with Storable

### ISSUE THREAD

**Issue by mkawalec** [lehins/massiv#40]
https://github.com/mkawalec/raytracer/blob/master/src/Lib.hs#L105 is a very hot array, so hopefully changing it to `S` would bring a significant speedup. However, after making it a `Storable`, I've noticed in Core that GHC stopped unpacking virtually all the parameters and because of constant boxing and unboxing on every call boundary the code is slightly slower than the `Boxed` representation. I've played with switches to SpecConstr, but I didn't notice any change whatsoever from tuning them. Do you know what could cause the optimizer to trip when `Storable` is used?

In Core, the code goes from
```
$w$scolor
  :: Double#
     -> Double#
     -> Double#
     -> Double#
     -> Double#
     -> Double#
     -> Int#
     -> Array# Sphere
     -> PCG32
     -> Int
     -> (# Double#, Double#, Double# #)
$w$scolor
  = \ (ww :: Double#)
      (ww1 :: Double#)
      (ww2 :: Double#)
      (ww3 :: Double#)
      (ww4 :: Double#)
      (ww5 :: Double#)
      (ww6 :: Int#)
      (ww7 :: Array# Sphere)
      (w :: PCG32)
      (w1 :: Int) ->
      let {
        a :: Double#
        a = +## (+## (*## ww3 ww3) (*## ww4 ww4)) (*## ww5 ww5) } in
```

to
```
$scolor :: Ray -> World Sphere -> PCG32 -> Int -> V3
$scolor
  = \ (eta :: Ray)
      (eta1 :: World Sphere)
      (eta2 :: PCG32)
      (eta3 :: Int) ->
      case eta of { Ray dt1 dt2 dt3 dt4 dt5 dt6 ->
      case eta1 `cast` <Co:5> of nt12 { SArray ipv ipv1 ipv2 ->
      case ipv1 of { I# y ->
      case ipv2 of { Vector dt7 dt8 dt9 ->
```
after switching the Array to `Storable`

**Comment by lehins** [comment]
That's a very interesting question. I don't understand how using storable could affect unpacking of other arguments, but I'd be curious to find out why it does that, if that is indeed the reason.

You can try using `U`nboxed array, see if that changes anything. It is a bit of a pain to create `Unbox` instances, but you could take care of a lot of boiler plate with [vector-th-unbox](http://hackage.haskell.org/package/vector-th-unbox) package. 

Another idea that comes to mind, which is probably completely off, could splitting in separate modules could have had an affect on unpacking or is it really only changing the array type from `B` to `S` causes GHC to stop the unpacking?

**Comment by mkawalec** [comment]
The only thing I'm changing here is the letter `B` to letter `S`. I will give `Unbox` a try later and report here.

**Comment by mkawalec** [comment]
After some play and great pointers from friends I found the culprit - the worker/wrapper optimization in GHC has a limit of ten parameters to a function by default. Unfortunately the `S` representation needs to pass a pointer to the data when unpacked and so trips the limiter since the optimized function would have 11 parameters. `{-# OPTIONS_GHC -fmax_worker_args=20 #-}` fixes it beautifully, you can close the issue now :)

**Comment by lehins** [comment]
This is awesome. I think I've seen that flag somewhere before, but now I know what it means ;) Thank you!
