### ISSUE TITLE
Conflict with Prelude's map; update README with clarification?

### ISSUE THREAD

**Issue by bbarker** [lehins/massiv#44]
Probably a Haskell-newbie issue, but I'm wondering what the recommended way to deal with the conflict between Haskell's and Prelude's `map`; performance aside, it seems like the Massiv `map` may be needed at times, unless I'm interpreting my errors incorrectly. My current solution which works for my small example is:

```haskell
import               Prelude hiding (map)
import               Data.Massiv.Array as AM
```

But I don't know if this is ideal. Thanks!

**Comment by lehins** [comment]
@bbarker it's a pretty common pattern for libraries to define functions that conflict with Prelude's, with the most common one being `map` :) If you look at extremely common packages `containers`, `vector`, `bytestring`, etc. you'll see the same pattern.

There are a few different ways to go about this conflict resolution thing. One of which is just to import the library modules `qualified`, but my personal favorite one being (following your example):
```haskell
import               Prelude as P
import               Data.Massiv.Array as AM
```
Then you can just pick and choose where the conflicting functions should come from
```haskell
foo :: [Int] -> Array D Ix2 Int -> ([Int], Array D Ix2 Int)
foo ls arr = (P.map succ ls, AM.map succ arr)
```

It is a very common thing in Haskell. :) In the matter of fact, it is so common, I even mention a small bit about it at the end of introduction in massiv: https://hackage.haskell.org/package/massiv-0.2.1.0/docs/Data-Massiv-Array.html#description

Cheers.
PS. Feel free to submit a PR with more documentation/explanation if you feel like it can be improved.
