### ISSUE TITLE
MArray usage

### ISSUE THREAD

**Issue by bbarker** [lehins/massiv#46]
Hello,

I was looking at the hackage `MArray` [docs](https://hackage.haskell.org/package/massiv-0.2.1.0/docs/Data-Massiv-Array-Mutable.html) and am somewhat confused, probably partly because the docs aren't yet as extensive as for immutable Arrays (especially with regard to examples), and partly because I'm still a beginner with Haskell.

So for something more concrete, I'm looking at `new`.

I'll try to write up some docs at some point, if it helps, after I get a bit further along (even if it is just restating what is in this issue).  I frequently see ` PrimMonad m`, but what are some example `m` types. How does one call `new` in an analogous way to the example: `makeArray Seq (3 :. 4) (\ (i :. j) -> if i == j then i else 0) :: Array D Ix2 Int`?

My goal is to create a large matrix, which I can then modify by doing some for of slice-base indexing to interact with submatrices. 

Thanks!

**Comment by lehins** [comment]
Hey @bbarker, I'd like to say this sort of questions don't normally belong in github issues. Tickets here are meant for actual problems or possible improvements to the library. Even if it is something like "We need more examples added to the docs", which seems like what this ticket is hinting at. But regular "how to use a library?" sort of question belong on other sites, for example gitter for simple one-off questions, or stackoverflow for something that could potentially be useful for others. If you ever do ask a question about massiv on stackoverflow, feel free to tag me, I'll be happy to try to provide an answer.

As far as this question goes. In `base` there are only two monads `m` that have instance of `PrimMonad m`, which are [`IO`](https://downloads.haskell.org/~ghc/8.4.3/docs/html/libraries/base-4.11.1.0/System-IO.html#t:IO) and [`ST s`](https://downloads.haskell.org/~ghc/8.4.3/docs/html/libraries/base-4.11.1.0/Control-Monad-ST.html#t:ST), plus all the monads from `transformers`.  So, for example here are the two possible monads for `new`:

```haskell
λ> :t new 10 :: IO (MArray RealWorld U Ix1 Int)
new 10 :: IO (MArray RealWorld U Ix1 Int) :: IO (MArray RealWorld U Ix1 Int)
λ> import Control.Monad.ST
λ> :t new 10 :: ST s (MArray s U Ix1 Int)
new 10 :: ST s (MArray s U Ix1 Int) :: ST s (MArray s U Ix1 Int)
```
It is easy to do all of the mutable stuff in IO, but keep in mind, all of the mutable operations on `MArray` aren't automatically parallelized. On the other hand it allows for common imperative style programming:
```haskell
λ> marr <- new (2 :. 5) :: IO (MArray RealWorld U Ix2 Int)
λ> write marr (1 :. 4) 217
True
λ> write marr (10 :. 4) 100 -- out of bounds
False
λ> freeze Seq marr
(Array U Seq (2 :. 5)
  [ [ 0,0,0,0,0 ]
  , [ 0,0,0,0,217 ]
  ])
```
Keep in mind, that most of the time you don't need to drop to mutable interface, majority of operations can be done in pure fashion.

If you ever decide to improve documentation, again, feel free to open a PR. I'm closing this ticket as a non-issue.
