### ISSUE TITLE
Sorting massiv arrays

### ISSUE THREAD

**Issue by ocramz** [lehins/massiv#48]
Are there sorting algorithms implemented already for `massiv`? Thanks!

**Comment by lehins** [comment]
@ocramz Not yet. It's definitely one of many things on my wish list for massiv. Not sure if it would be better to create a separate package `massiv-algorithms`, that would contain things like sorting, but I am leaning more towards `massiv` being "batteries included" kind of library.

I'll convert this ticket into a feature request.

**Comment by lehins** [comment]
For now it is only quicksort that is implemented, but it is a start. See related benchmarks in helper repo: https://github.com/lehins/haskell-quicksort as well as related SO answer: https://stackoverflow.com/questions/19752983/is-it-possible-to-speed-up-a-quicksort-with-par-in-haskell/55885118#answer-55885118
