### ISSUE TITLE
Add massiv benchmarks in `haskell-perf`

### ISSUE THREAD

**Issue by ocramz** [lehins/massiv#49]
It would be very informative to have massiv featured alongside vector in the `haskell-perf/sequences` benchmark suite

https://github.com/haskell-perf/sequences

**Comment by lehins** [comment]
@ocramz Interesting coincidence, I brought this up at work when talking to @chrisdone last week.

Some of the features, like filtering or [sorting](https://github.com/lehins/massiv/issues/48) aren't currently available in `massiv`, but it be nice to have benchmarks at least for operations that are available in that list.

It would also be great to have benchmarks on `haskell-perf` that compare array libraries as well (Repa, accelerate, yarr ...), which is sort of in the works in `massiv-benchmarks`, but those are nowhere near to being done.

**Comment by ocramz** [comment]
Closing this for now! :)
