### ISSUE TITLE
upload massive-0.2.3.0 to hackage

### ISSUE THREAD

**Issue by madjestic** [lehins/massiv#53]
Hey guys,

Is there a reason why 0.2.3.0 is not uploaded to hackage yet?

Cheers,
Vlad

**Comment by lehins** [comment]
@madjestic, waiting for CI to pass on #51 and will then upload it, so tune in. ;)

**Comment by madjestic** [comment]
Kewl.  I would like to add it to submit it to gentoo repo as soon as that's done.

Thanks! ;)

**Comment by lehins** [comment]
@madjestic `massiv-0.2.3.0` is up on hackage.
