### ISSUE TITLE
Confused by ``traverse``

### ISSUE THREAD

**Issue by kozross** [lehins/massiv#57]
I'm not sure I understand how this function would actually be used. I _vaguely_ get that this is designed to be a version of ``makeArray`` that's augmented by having access to another auxiliary array that it can make use of, but I have no idea how you are meant to make use of that array. I'm particularly confused by the second argument. Would you be able to explain, or perhaps give an example?

**Comment by lehins** [comment]
This sort of questions aren't meant to be submitted as github issues. There is gitter and of course stackoverflow. See a similar answer I made on another ticket: https://github.com/lehins/massiv/issues/46#issuecomment-427031401 I'll still answer it though.

`traverse` in massiv was inspired by `traverse` function in Repa library, with a slight modification. Here is an example of how to write transpose with it:
```haskell
λ> arr = makeArrayR P Seq (5 :. 4) (toLinearIndex (5 :. 4))
λ> arr
(Array P Seq (5 :. 4)
  [ [ 0,1,2,3 ]
  , [ 4,5,6,7 ]
  , [ 8,9,10,11 ]
  , [ 12,13,14,15 ]
  , [ 16,17,18,19 ]
  ])
λ> traverse (4 :. 5) (\ f (i :. j) -> f (j :. i)) arr
(Array D Seq (4 :. 5)
  [ [ 0,4,8,12,16 ]
  , [ 1,5,9,13,17 ]
  , [ 2,6,10,14,18 ]
  , [ 3,7,11,15,19 ]
  ])
```

With all honesty this function brings more confusion than usefulness, so if you still don't get it, don't worry about it.
