### ISSUE TITLE
How to get the average from the non-convolution stencil example?

### ISSUE THREAD

**Issue by kozross** [lehins/massiv#58]
In the README, there's an example of an averaging stencil, which is first described without convolution, and then with. However, only the convolution example has an explanation of how to get the average out of it, while the non-convolution one doesn't. What would be the way to get the average from the non-convolution example, once ``mapStencil`` had been applied?

**Comment by lehins** [comment]
Same as in #57 in regards to questions.

Not sure what you mean by non-convolution example does not explain how to get average out of it? Could you clarify it a bit more?

Here is the stencil that will compute the average, once mapped over an array.
```haskell
average3x3Filter :: (Default a, Fractional a) => Stencil Ix2 a a
average3x3Filter = makeStencil (3 :. 3) (1 :. 1) $ \ get ->
  (  get (-1 :. -1) + get (-1 :. 0) + get (-1 :. 1) +
     get ( 0 :. -1) + get ( 0 :. 0) + get ( 0 :. 1) +
     get ( 1 :. -1) + get ( 1 :. 0) + get ( 1 :. 1)   ) / 9
{-# INLINE average3x3Filter #-}
```

In order to apply it to an array you just use `mapStencil` and then `compute` the resulting delayed windowed array:
```haskell
computeAs U (mapStencil Edge average3x3Filter arr :: Array DW Ix2 Double)
```

**Comment by kozross** [comment]
I guess my understanding of the average stencil was that, after everything is done, you would get a single value, which is the average of all array elements. However, from what I can see, after you run ``computeAs U (mapStencil Edge average3x3Filter arr :: Array DW Ix2 Double)``, you'd get an array containing all the values, rather than a single average. Am I right in that regard?

**Comment by lehins** [comment]
Yes, your initial understanding of the stencil was an incorrect one. Stencil uses the neighborhood elements of the source array to produce elements of the target array. So, yes you are right in that regard. Above example will produce a new array with each element being an average of 9 element from the source array around the same index.
