### ISSUE TITLE
Introduce github templates with contribution guidelines (both PRs and issues)

### ISSUE THREAD

**Issue by kozross** [lehins/massiv#61]
I'd like to contribute to massiv, specifically regarding #60, #56, #48 and some other things which I've found useful. Are there any requirements for code submitted as a PR here? For example:

* HLint
* Specific versions of GHC we should be compatible with
* Code formatting requirements, such as use of a formatter

I'd rather not create extra work for you if I can avoid it.

**Comment by lehins** [comment]
Really glad to hear that you are willing to contribute to `massiv`. 
The question you bring up is a totally legit one, and I will construct some github templates in near future. I'll change the title of the ticket and make it a task for myself so I don't forget to do that.

Here is short rundown if suggestions/requirement from the top of my head:
* `hlint` is an amazing tool and I'd certainly recommend running it, but it is not a requirement by any means.
* Specific versions of ghc that must be supported can be deduced from the `.travis.yaml` file. As of today these are 7.10 - 8.6. This reminds me that I need to add 8.6 to the build matrix. Yay, for longer CI builds.
* Code formatting is the simple one. Almost everywhere I use `hindent` for functions formatting and `stylish-haskell` for organizing the imports. Default setting for the above tools should be just fine.
* The important parts are the:
  * Clear documentation, preferably with examples
  * As many unit tests and quickcheck properties in the test suite as possible. Cause those not only can be used to deduce the desired behavior of new functionality, but also validate that it conforms to it.

Thank you in advance for your contributions.
