### ISSUE TITLE
Bug I the convolution functions?

### ISSUE THREAD

**Issue by jrp2014** [lehins/massiv#72]
Here is a simple example:

```
    1 module Massiv where
    2 
    3 import Data.Massiv.Array as A
    4 
    5 xs :: A.Array A.U A.Ix1 Int
    6 xs = A.fromList A.Seq [1, 2, 3, 4] 
    7 
    8 ys :: A.Array A.U A.Ix1 Int
    9 ys = A.fromList A.Seq [1, 2, 3, 4, 5] 
   10 
   11 zs :: A.Array A.D A.Ix1 Int
   12 zs = A.range A.Seq 20001 30000
   13 
   14 stencil :: A.Stencil A.Ix1 Int Int
   15 stencil = makeConvolutionStencilFromKernel xs
   16 
   17 result :: Array U Ix1 Int
   18 result = A.computeAs A.U (A.mapStencil (A.Fill 0) stencil ys)
```
`result` comes out as `(Array U Seq (5) [ 10,20,30,4510889970,31 ])`.  If I swap `xs` and `ys` in 15 and 18 I get `(Array U Seq (4) [ 10,20,30,34 ])`.

Perhaps with appropriate 0 padding, I was expecting ` [1, 4, 10, 20, 30, 34, 31, 20]`.  Some of this is clearly the fact that the built-in stencil-creation functions are centred with image filters, rather than, eg, digital signals / FIR, in mind.  But the `4510889970` looks odd either way.

**Comment by lehins** [comment]
It looks like a bug in `makeConvolutionStencilFromKernel` function. I am out travelling right now, but will look at it in a day or two. Thank you for this report.

**Comment by lehins** [comment]
So, as I suspected, there was a bug `makeConvolutionStencilFromKernel`, which surfaced whenever kernel was not odd in size, i.e. kernel didn't have a proper center. I did fix that issue.

@jrp2014  Thank you for bringing this issue to my attention, it motivated me to write some proper tests for convolution and correlation, which resulted in me finding and fixing couple other issues. If you get a chance, could you please checkout the [massiv-0.2.8](https://github.com/lehins/massiv/compare/massiv-0.2.8) branch and confirm that the issue has indeed been fixed?

With regards to zero padding, thus increasing the resulting array size, could be a potential feature addition to massiv, but currently `mapStencil` will produce the same size array as the array to which the stencil is being applied to.

**Comment by jrp2014** [comment]
Thanks.  That seems to work (although the results are still truncated by the absence of padding):
```
*Data.Massiv.Array> import Data.Massiv.Array as A
*Data.Massiv.Array A> let xs = A.fromList A.Seq [1, 2, 3, 4]  :: A.Array A.U A.Ix1 Int
*Data.Massiv.Array A> let ys = A.fromList A.Seq [1, 2, 3, 4, 5] :: A.Array A.U A.Ix1 Int
*Data.Massiv.Array A> let s = (makeConvolutionStencilFromKernel xs) ::  A.Stencil A.Ix1 Int Int
*Data.Massiv.Array A>  A.computeAs A.U (A.mapStencil (A.Fill 0) s ys)
Array U Seq (Sz1 5)
  [ 10, 20, 30, 34, 31 ]
*Data.Massiv.Array A> let s = (makeConvolutionStencilFromKernel ys) ::  A.Stencil A.Ix1 Int Int

<interactive>:8:5: warning: [-Wname-shadowing]
    This binding for ‘s’ shadows the existing binding
      defined at <interactive>:6:5
*Data.Massiv.Array A>  A.computeAs A.U (A.mapStencil (A.Fill 0) s xs)
Array U Seq (Sz1 4)
  [ 10, 20, 30, 34 ]
```

**Comment by lehins** [comment]
@jrp2014 Thank you for confirming it.

I will make a `massiv-0.2.8.0` release containing the fix shortly.

The result is not really truncated, it just doesn't grow, so it does behave as intended. Note that the source and result vectors are of the same length, which is most common way to do discrete convolution on finite arrays (at least from my experience in image processing).

That being said, I don't see a reason why we can't have such a function that grows the result array according to border resolution technique (eg. `Fill`) and the supplied stencil. I'll add it in a future release. I think a good name for it would be `applyStencil`.

**Comment by jrp2014** [comment]
Thanks.  While it might not be useful for images, DSP processing and an efficient DFT/FFT can benefit from padding.
