### ISSUE TITLE
error: • No instance for (Ragged DI Ix1 Double) arising from a use of ‘empty’

### ISSUE THREAD

**Issue by xxAVOGADROxx** [lehins/massiv#74]
I am trying to generate a vector using specific values, for this I read the documentation in  
[Hackage](http://hackage.haskell.org/package/massiv-0.3.0.1/docs/Data-Massiv-Array.html#g:2). First, I tried to generate a singleton array and add values, in the same way given by the example, but the following error appears:
```
λ> import Data.Massiv.Array as A
λ> singleton 7 :: Array D Ix4 Double

<interactive>:218:1-11: error:
    • Couldn't match expected type ‘Array D Ix4 Double’
                  with actual type ‘e0 -> Array r0 ix0 e0’
    • In the expression: singleton 7 :: Array D Ix4 Double
      In an equation for ‘it’: it = singleton 7 :: Array D Ix4 Double
λ> 
```
So, I tried to generate a empty array, but I have an scope and instance error.

```
λ>  import Data.Massiv.Array as A
λ> :set -XTypeApplications
λ> xs = empty @DL @Ix1 @Double

<interactive>:212:13-14: error:
    Not in scope: type constructor or class ‘DL’
    Perhaps you meant one of these:
      ‘D’ (imported from Data.Massiv.Array),
      ‘DI’ (imported from Data.Massiv.Array),
      ‘DW’ (imported from Data.Massiv.Array)
λ> xs = empty @D @Ix1 @Double

<interactive>:213:6-26: error:
    • No instance for (Ragged D Ix1 Double)
        arising from a use of ‘empty’
    • In the expression: empty @D @Ix1 @Double
      In an equation for ‘xs’: xs = empty @D @Ix1 @Double

```
I am using massive 0.3.0.1 package version and ghc 8.6.4

**Comment by lehins** [comment]
Are you sure you are using `massiv-0.3.0.1`? From the errors I can deduce 100% that this is `massiv-0.2.x`. I've added doctests in version `massiv-0.3`, so I know examples work, but here is how I know it's not the latest version:
* `singleton` function used to take 2 arguments, where now it takes only one argument.
* `DL` type was introduced in `0.3.0.0`
* `empty` was a different function in `0.2` and was renamed to `emptyRagged` and made internal. Ragged interface isn't quite ready for usage and was exported unintentionally.

Feel free to reopen it if you still think there is a problem with the library

**Comment by xxAVOGADROxx** [comment]
Thank you very much for your answer indeed the version of the package was outdated
