### ISSUE TITLE
Typo in documentation: fasion should be fashion

### ISSUE THREAD

**Issue by noughtmare** [lehins/massiv#81]
Searching for fasion on GitHub gives me three results:

https://github.com/lehins/massiv/blob/0a317553fded955515f824a65d96337ead1d0d69/massiv/src/Data/Massiv/Array/Delayed/Interleaved.hs#L27

https://github.com/lehins/massiv/blob/9654034ba979affd1e2e23253d9046ade72251e9/massiv/src/Data/Massiv/Core/Common.hs#L99

https://github.com/lehins/massiv/blob/9654034ba979affd1e2e23253d9046ade72251e9/massiv/src/Data/Massiv/Core/Common.hs#L201

But I know GitHub search is not always very good so it might be wrong in more places.

**Comment by lehins** [comment]
Thanks.
